//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class live2d_AMotionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(live2d.AMotion), typeof(System.Object));
		L.RegFunction("setFadeIn", setFadeIn);
		L.RegFunction("setFadeOut", setFadeOut);
		L.RegFunction("setWeight", setWeight);
		L.RegFunction("getFadeOut", getFadeOut);
		L.RegFunction("getFadeIn", getFadeIn);
		L.RegFunction("getWeight", getWeight);
		L.RegFunction("getDurationMSec", getDurationMSec);
		L.RegFunction("getLoopDurationMSec", getLoopDurationMSec);
		L.RegFunction("getEasing", getEasing);
		L.RegFunction("updateParam", updateParam);
		L.RegFunction("updateParamExe", updateParamExe);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setFadeIn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.setFadeIn(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setFadeOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.setFadeOut(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setWeight(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.setWeight(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getFadeOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			int o = obj.getFadeOut();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getFadeIn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			int o = obj.getFadeIn();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getWeight(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			float o = obj.getWeight();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getDurationMSec(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			int o = obj.getDurationMSec();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getLoopDurationMSec(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			int o = obj.getLoopDurationMSec();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getEasing(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
			float o = live2d.AMotion.getEasing(arg0, arg1, arg2);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int updateParam(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			live2d.ALive2DModel arg0 = (live2d.ALive2DModel)ToLua.CheckObject<live2d.ALive2DModel>(L, 2);
			live2d.MotionQueueEnt arg1 = (live2d.MotionQueueEnt)ToLua.CheckObject<live2d.MotionQueueEnt>(L, 3);
			obj.updateParam(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int updateParamExe(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			live2d.AMotion obj = (live2d.AMotion)ToLua.CheckObject<live2d.AMotion>(L, 1);
			live2d.ALive2DModel arg0 = (live2d.ALive2DModel)ToLua.CheckObject<live2d.ALive2DModel>(L, 2);
			long arg1 = LuaDLL.tolua_checkint64(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			live2d.MotionQueueEnt arg3 = (live2d.MotionQueueEnt)ToLua.CheckObject<live2d.MotionQueueEnt>(L, 5);
			obj.updateParamExe(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

